### ISSUE TITLE
Worked fine yesterday, but showing error for me today.

### ISSUE THREAD

**Issue by paulaai** [gurugaurav/bing_image_downloader#31]
I've tried this yesterday with a couple of queries and it worked completely fine. But today it is showing some error - 

```
Traceback (most recent call last):
  File "E:\Pyhon\bing.py", line 1, in <module>
    from bing_image_downloader import downloader
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\bing_image_downloader\downloader.py", line 6, in <module>
    from bing import Bing
  File "E:\Pyhon\bing.py", line 2, in <module>
    downloader.download('apricot', limit=100,  output_dir='dataset', adult_filter_off=True, force_replace=False, timeout=60, verbose=True)
AttributeError: partially initialized module 'bing_image_downloader.downloader' has no attribute 'download' (most likely due to a circular import)

Process finished with exit code 1
```

**Comment by mehanalavimajd** [comment]
Installed today. Same error.

**Comment by spider853** [comment]
same here on second run,....

**Comment by gurugaurav** [comment]
@spider853  @mehanalavimajd  can u please give the step to reproduce this error

**Comment by Herschel-vodemort** [comment]
for those who still run into this issue in 2023, this fixed my problem:
```
from bing_image_downloader.downloader import  download
download('map', limit=100,  output_dir='dataset', adult_filter_off=True, force_replace=False, timeout=60, verbose=True)
```
